# Generated by Django 4.2.7 on 2023-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='no_picture.png', upload_to='users'),
        ),
    ]
